### PR TITLE
Split first when parsing procfile

### PR DESCRIPTION
**Pull request by i-like-robots**
So we can do things like:

```
# Procfile
web: export PATH=$PATH:/app/.whatever/bin; forever -c 'node --harmony' app.js
```

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i need to tidy up this repo……

in the mean time do you mind pulling your branch  into nbt?

https://github.com/Financial-Times/next-build-tools/blob/master/package.json#L20

**Comment by i-like-robots** [comment]
As a side note, this change is necessary because we're [not currently bundling dot-prefixed dirs](https://github.com/matthew-andrews/haikro/pull/84) so we can't dump binaries in `.heroku/vendor`- though this does have the side-effect of avoiding copying across `.travis/`...

**Comment by matthew-andrews** [comment]
going to close this…  should be possible now we use DOCKER

**Comment by matthew-andrews** [comment]
@i-like-robots is this necessary again now we have ditched docker?

**Comment by i-like-robots** [comment]
I think so - here's where it's needed: https://github.com/Financial-Times/next-article/blob/master/Procfile#L1

Now we can bundle dot-prefixed files and folders maybe we can just move `libxslt/` to  `.travis/`.

**Comment by matthew-andrews** [comment]
I'll need to update NBT to use haikro 2 to do this.

**Pull request closed without merging**
